package com.padre.reportescotizadortelcel_v2.mapper;

import com.padre.reportescotizadortelcel_v2.domain.CotizacionesFuerzaVentaDat;
import com.padre.reportescotizadortelcel_v2.domain.DetalleCotizacionDats;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface CotizacionesFuerzaVentaDatMapper {

    @Select("Select FORMA_PAGO AS TIPO,ID_COTIZACION as IDCOTIZACION,FECHA_HORA_REGISTRO as FECHAHORAREGISTRO,BES_COTIZACION.REGION,CUDG_CO_USUARIO.NOMBRE, CORREO_ENVIO as correoEnvio,BES_OFERTASUPLEMENTARIA.OFFERING_NAME as ofertaSuplementaria, BES_OFERTAPRIMARIA.OFFERING_NAME as ofertaPrimaria,BES_COTIZACION.PLAZO,CUDG_CO_DISTRIBUIDOR.DESCRIPCION from BES_COTIZACION left join CUDG_CO_USUARIO on BES_COTIZACION.ID_USUARIO= CUDG_CO_USUARIO.ID left join CUDG_CO_DISTRIBUIDOR on CUDG_CO_USUARIO.ID_DISTRIBUIDOR = CUDG_CO_DISTRIBUIDOR.ID_DISTRIBUIDOR left join BES_OFERTASUPLEMENTARIA on BES_COTIZACION.ID_OFERTASUPLEMENTARIA= BES_OFERTASUPLEMENTARIA.SUPLE_OFFERING_ID left join BES_OFERTAPRIMARIA on BES_COTIZACION.ID_OFERTAPRIMARIA= BES_OFERTAPRIMARIA.PRIMARY_OFFERING_ID where (FECHA_HORA_REGISTRO between '05/04/22 09:00:00.00000000' and '05/04/22 23:59:00.000000000') and ((CORREO_ENVIO not in (select * from table(split((select valor from cudg_co_parametros where titulo = 'CORREOS_PRUEBA'),'|'))) or CORREO_ENVIO is null))AND tramite_canal like '%DAT%' ORDER BY ID_COTIZACION desc")
    List<CotizacionesFuerzaVentaDat> findCotizacionesFuerzaVentaDat();

    @Select("SELECT ID_COTIZACION as IDCOTIZACION, ID_USUARIO as IDUSUARIO, IP, FORMA_PAGO as FORMAPAGO, PRECIO, PRECIO_IVA as PRECIOIVA, PRECIO_SUBSIDIO as PRECIOSUBSIDIO, PRECIO_SUBSIDIO_IVA as PRECIOSUBSIDIOIVA, PRECIO_SIN_SUBSIDIO as PRECIOSINSUBSIDIO,PRECIO_SIN_SUBSIDIO_IVA as PRECIOSINSUBSIDIOIVA, FECHA_HORA_REGISTRO as FECHAHORAREGISTRO, CORREO_ENVIO as CORREOENVIO, ID_OFERTAPRIMARIA as IDOFERTAPRIMARIA,ID_OFERTASUPLEMENTARIA as IDOFERTASUPLEMENTARIA, REGION, IVA, SOBREPRECIO, CARGO_EQUIPO as CARGOEQUIPO, CARGO_EQUIPO_IVA as CARGOEQUIPOIVA, IDENTIFICADOR_UNO as IDENTIFICADORUNO, IDENTIFICADOR_DOS as IDENTIFICADORDOS, IDENTIFICADOR_TRES as IDENTIFICADORTRES, PLAZO, SKU, COLOR, ENVIADO FROM bes_COTIZACION where ID_RENOVACION_DAT is not null and  (FECHA_HORA_REGISTRO between '05/04/22 00:00:00.00000000' and '05/04/22 23:59:00.000000000') and ((CORREO_ENVIO not in (select * from table(split((select valor from cudg_co_parametros where titulo = 'CORREOS_PRUEBA'),'|'))) or CORREO_ENVIO is null)) AND tramite_canal like '%DAT%'")
    List<DetalleCotizacionDats> findDetalleCotizacionDats();
}
